default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost
  prepared_statements: false

development:
  <<: *default
  port:  5432
  database: payment_app_development
test:
  <<: *default
  port: 5432
  database: payment_app_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
